"""
Agent State — Canonical state container for the LangGraph StateGraph.

This TypedDict defines every field that flows between agent nodes.
All agents read from and write to this shared state object.

Reference: Architecture Document Section 7.1

Image Input Upgrade:
  Added image_path, image_analysis, image_summary, components,
  observations, possible_issues, and domain fields to support
  user-uploaded image analysis via the Vision Agent.
"""

from typing import TypedDict, List, Dict, Any, Optional


class AgentState(TypedDict):
    """
    Shared state passed through all nodes in the LangGraph StateGraph.

    Lifecycle:
      1. User query enters → `query` is set, all other fields initialised.
      2. Context Router reads `query` (or `refined_query` on loopback) → sets `intent`.
      3. Retrieval agents populate `text_results` and/or `image_results`.
      4. Synthesis agent generates `final_answer`, runs verification.
      5. If verification fails and loopback_count < MAX_LOOPBACKS,
         the graph loops back to the router with `refined_query`.
    """

    # ── Session & Memory ────────────────────────────────────────────────
    session_id: str
    """
    Unique identifier for the current conversation session.
    Used to track state across multi-turn interactions and
    correlate logs for debugging.
    """

    session_history: List[Dict[str, str]]
    """
    Chronological list of prior turns in this conversation session.
    Each dict has keys: {"role": "user"|"assistant", "content": "..."}.
    Enables follow-up query resolution (e.g. "What resistor value
    should I use for that LED?" requires knowing the prior context).
    The Router and Synthesis agents consume this for continuity.
    """

    # ── Inputs & Routing ────────────────────────────────────────────────
    query: str
    """The original user input query. Never mutated after initial assignment."""

    refined_query: Optional[str]
    """
    An improved search query generated by the Synthesis agent during
    a loopback cycle. The Router and retrieval agents should prefer
    this over `query` when it is not None.
    """

    intent: str
    """
    Intent classification from the Context Router or Vision Agent.
    One of: "text", "visual", "both", "clarify".
    """

    # ── Image Input ──────────────────────────────────────────────────
    image_path: Optional[str]
    """
    Temporary file path to the uploaded image. Set by the API layer.
    The Vision Agent reads this file, then the API layer deletes it
    after graph execution completes.
    """

    image_analysis: Optional[Dict[str, Any]]
    """
    Structured JSON output from the Vision Agent. Contains:
      domain, intent, summary, components, observations, possible_issues.
    Stored as a dict so downstream agents can access any field.
    """

    image_summary: Optional[str]
    """Human-readable summary of what the uploaded image contains."""

    components: List[str]
    """List of electronic components identified in the uploaded image."""

    observations: List[str]
    """Visual observations about the circuit/setup in the image."""

    possible_issues: List[str]
    """Potential problems identified in the image (e.g. reversed LED polarity)."""

    domain: Optional[str]
    """
    Domain classification from the Vision Agent.
    'electronics' — image contains circuits, boards, components.
    'general'     — screenshot, browser error, non-electronics image.
    """

    # ── Context Pools ───────────────────────────────────────────────────
    text_results: List[Dict[str, Any]]
    """
    Chunks retrieved by the Hybrid Retrieval Agent (BM25 + dense + RRF).
    Each dict contains: chunk_id, text, score, source_document, section_name.
    """

    image_results: List[Dict[str, Any]]
    """
    Images retrieved by the Visual Retrieval Agent (CLIP cross-modal search).
    Each dict contains: image_id, image_path, caption, score, source_document.
    """

    # ── Agent Outputs ───────────────────────────────────────────────────
    clarification_question: Optional[str]
    """
    A follow-up question generated by the Clarification Agent when the
    user's query is too vague or ambiguous to retrieve meaningful results.
    """

    final_answer: Optional[str]
    """
    The fully synthesized answer produced by the Synthesis Agent.
    Includes cited source documents and optional image references.
    """

    # ── Sources & Citations ─────────────────────────────────────────────
    sources: List[str]
    """
    List of source document names cited in the final answer.
    Populated by the Synthesis Agent during answer generation.
    Used for grounded citations, frontend rendering, and
    retrieval quality evaluation.
    """

    # ── Loopback & Quality Controls ─────────────────────────────────────
    verification_passed: bool
    """
    Flag set by the Synthesis Agent after self-verification.
    True = answer is complete and grounded. False = needs loopback.
    """

    verification_feedback: Optional[str]
    """
    When verification fails, the Synthesis Agent writes specific reasons
    here (e.g., "answer lacks pinout details"). This feedback is passed
    to the Router on loopback to guide refined retrieval.
    """

    loopback_count: int
    """
    Counter tracking the number of self-correction cycles completed.
    Capped at MAX_LOOPBACKS (3) to prevent infinite loops.
    """


# ── Constants ───────────────────────────────────────────────────────────
MAX_LOOPBACKS = 1
"""Maximum number of self-correction loopback cycles allowed."""


def create_initial_state(
    query: str,
    session_id: Optional[str] = None,
    session_history: Optional[List[Dict[str, str]]] = None,
    image_path: Optional[str] = None,
) -> AgentState:
    """
    Factory function to create a properly initialised AgentState
    from a raw user query string.

    Args:
        query:           The user's input question.
        session_id:      Optional session identifier. Auto-generated if None.
        session_history: Optional prior conversation turns for follow-up context.
        image_path:      Optional path to a temporary uploaded image file.

    Usage:
        state = create_initial_state("How do I configure SPI on Arduino?")
        state = create_initial_state(
            "What resistor for that LED?",
            session_id="abc-123",
            session_history=[{"role": "user", "content": "How to wire an LED?"},
                            {"role": "assistant", "content": "Use a 220Ω resistor..."}],
        )
        state = create_initial_state(
            "Why isn't this working?",
            image_path="/tmp/upload_abc123.png",
        )
    """
    import uuid
    if session_id is None:
        session_id = str(uuid.uuid4())
    return AgentState(
        session_id=session_id,
        session_history=session_history or [],
        query=query,
        refined_query=None,
        intent="",
        text_results=[],
        image_results=[],
        sources=[],
        clarification_question=None,
        final_answer=None,
        verification_passed=False,
        verification_feedback=None,
        loopback_count=0,
        # Image input fields
        image_path=image_path,
        image_analysis=None,
        image_summary=None,
        components=[],
        observations=[],
        possible_issues=[],
        domain=None,
    )
